version: '3'

services:
    database:
      image: mysql
      volumes:
        - ./init:/docker-entrypoint-initdb.d
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: spaces
        MYSQL_DATABASE: contosodb
        MYSQL_USER: contoso
        MYSQL_PASSWORD: spaces
    admin:
      build: .
      restart: always
      ports:
        - 4000:80
      environment: 
        MYSQL_CONNECTION_STRING: Server=datbase;Database=contosodb;Uid=contoso;Pwd=spaces;