version: '3'

services:
    database:
      image: msusdev/mslearn-contoso.spaces.database
      restart: always
    web:
      image: msusdev/mslearn-contoso.spaces.web
      restart: always
      depends_on:
        - database
      ports:
        - 80:80
      environment: 
        MYSQL_CONNECTION_STRING: mysql://contoso:spaces@database:3306/contosodb