name: Publish to Docker Hub
on:
  push:
    branches: [ main ]
jobs:
  publish:
    name: Publish Docker Hub image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Get date tag
        id: tag
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push to Docker Hub
        id: push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            msusdev/mslearn-contoso.spaces.web:latest
            msusdev/mslearn-contoso.spaces.web:${{ steps.tag.outputs.date }}
      - name: Image digest
        run: echo ${{ steps.push.outputs.digest }}